const lastYear = new Date().getFullYear() - 1;
export const testData = [
  {
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },
  {
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  },{
    TubeVoltage:'80',
    mAs:'20.0',
    Dose:'---',
    ExposureTime:'---',
    TubeVoltagePeak:'---',
    ColumnX:'---',
    ColumnY:'---',
    ColumnZ:'---'
  }

];
